---
title: "Interactive Basketball Plots"
author: "Amy_Neal"
date: "2026-04-10"
output: 
  html_document: 
    keep_md: true
---

```{css, echo=FALSE}
@import url('https://fonts.googleapis.com/css2?family=Noto+Serif&display=swap');

body {
  font-family: 'Noto Serif', serif;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages 

```{r packages, warning=FALSE, message=FALSE}
library(hoopR) #basketball datasets
library(dplyr) #data manipulation
library(ggplot2) #graphing and visualization
library(tidyverse) #data manipulation
library(psych) #descriptive statistics
library(ggiraph) #interactive plots
```

# Import Dataset 

```{r NBA data}
nba_team_box <- hoopR::load_nba_team_box(2021:hoopR::most_recent_nba_season()) #save data from 2021 to current
```

## Isolate Hawks Data From Full Dataset 

```{r Hawks df}
hawks <- nba_team_box %>% #select from nba_team_box data 
  filter(team_id==1) %>% #select values where team = 1 
  mutate(game_date = as.Date(game_date)) %>% #convert game date variable to date type 
  arrange(game_date) %>% #order the dataframe by game 
  mutate(season = as.factor(season)) %>% #convert season variable to factor 
  mutate(team_home_away = recode(team_home_away, #recode home_away variable so values have capital letters 
                                 home = 'Home',
                                 away = 'Away'))
hawks_avg <- hawks %>%
  group_by(season) %>% #summarize by season
  summarize(mean_score = round(mean(team_score),0)) #average team scores
```

## Make Plot of Hawks Scores From 2021-2026

```{r Hawks graph}
hawks_plot <- ggplot(data = hawks, aes(x = season, y = team_score)) +
  geom_jitter_interactive(alpha = .7, 
                          aes(color = team_winner,
                              tooltip = paste0(`team_home_away`,
                                               ' vs. ', `opponent_team_abbreviation`,
                                               '\nFinal Score: ',`team_score`, '-', `opponent_team_score`))) +
  geom_point_interactive(data = hawks_avg,
                         aes(x = season, y = mean_score,
                             tooltip = paste0('Season Average: ', `mean_score`)),
                         color = 'black', shape = 17, size = 3) +
  theme_classic() +
  labs(x = 'Season',
       y = 'Hawks Score',
       color = 'Outcome',
       title = 'Atlanta Hawks Points Per Game 2021-2026') +
  theme(text = element_text(family = 'serif'),
        plot.title = element_text(size = 18),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 12),
        legend.position = 'bottom') +
  scale_color_manual(values = c('#C8102E', '#fdb927'), labels = c('Loss', 'Win'))
```

```{r hawks girafe, dpi=300, fig.width=8, fig.height=5}
girafe(hawks_plot)
```